[package]
name = "energy-monitor-lib"
authors = ["Michael Zill"]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
bytes = "1.6.0"
